sudo: required
language: node_js
dist: xenial
node_js:
- 10.22.0
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
install:
- yes n | npm install
- echo env(ENV_TYPE)
- |
  if [ env(ENV_TYPE) = "prod" ]; then
    cp src/environments/environment.prod.ts src/environments/environment.ts
  fi
- |
  if [ env(ENV_TYPE) != "prod" ]; then
    cp src/environments/environment.dev.ts src/environments/environment.ts
  fi
- npm run build
script:
- echo "skipping tests"
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -e "ssh -o StrictHostKeyChecking=no" -r dist/* $SB_WEB_HOST:~/switchboard-dapp/develop
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script: rsync -e "ssh -o StrictHostKeyChecking=no" -r dist/* $SB_WEB_HOST:~/switchboard-dapp/master
  on:
  branch: master
